### ISSUE TITLE
Reduce corpus payload on Argos

### ISSUE THREAD

**Issue by benel** [Hypertopic/Argos#54]
Some corpora are very long. `Vitraux - Bénel` for example – with 1.3 Mb and 7k lines – takes approximately 1.2s to load.

Hypertopic views use a ternary model such as this:

```json
{"rows":[
  {"key":["C"], "value":{"name":"N1"}},
  {"key":["C"], "value":{"user":"U1"}},
  {"key":["C"], "value":{"user":"U2"}},
  {"key":["C","I"], "value":{"name":"N2","resource":"http://acme/bar"}},
  {"key":["C","I"], "value":{"A":"V"}},
  {"key":["C","I"], "value":{"topic":{"viewpoint":"V1","id":"T1"}}},
  {"key":["C","I", "H"], "value":{"coordinates":[123,240], "topic":{"viewpoint":"V2", "id":"T2"}}}
]}
```

However other triples serialization are also equivalent such as:

```json
{"rows":[
  {"key":["C"], "value":{"name":"N1", "user":["U1", "U2"]}},
  {"key":["C","I"], "value":{"name":"N2","resource":"http://acme/bar", "A":"V"}},
  {"key":["C","I"], "value":{"topic":{"viewpoint":"V1","id":"T1"}}},
  {"key":["C","I", "H"], "value":{"coordinates":[123,240], "topic":{"viewpoint":"V2", "id":"T2"}}}
]}
```

Or even:

```json
{"rows":[
  {"key":["C"], "value":{"name":"N1", "user":["U1", "U2"]}},
  {"key":["C","I"], "value":{"name":"N2","resource":"http://acme/bar", "A":"V", "topic":{"viewpoint":"V1","id":"T1"}}},
  {"key":["C","I", "H"], "value":{"coordinates":[123,240], "topic":{"viewpoint":"V2", "id":"T2"}}}
]}
```

Such a compact syntax could reduce  payload by 1/3 or even 1/2.

Possible negative impacts:

- on the memory used by CouchDB to write and read the index (server lag),
- on compatibility with clients : 
  - Porphyry and LaSuli should be OK since this abstraction is handled by Hypertopic node library,
  - Agorae may not handle this until it uses the Hypertopic node library (@cahier @mTixier).

**Comment by garnier5** [comment]
After verification, I confirm that the changes do not impact Porphyry or LaSuli.
However, I'm not familiar with Agorae. Have you verified that these modifications don't impact Agorae? (@cahier @mTixier)

**Comment by benel** [comment]
Félicitations @garnier5 🥇 
Votre code est en production !
